name: Trigger Checkmarx DAST Scan

on:
  pull_request:
    branches:
      - main  # Trigger on pull request to 'main' branch

jobs:
  dast-scan:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the runner

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Trigger Checkmarx DAST scan using Checkmarx DAST GitHub Action
    - name: Checkmarx DAST GitHub Action
      uses: Checkmarx/dast-github-action@v2.3.0  # Using the latest version of the Checkmarx DAST GitHub Action
      with:
        command: web  # Perform a web scan
        base_url: ${{ secrets.CHECKMARX_API_URL }}  # URL for the Checkmarx instance (stored in secrets)
        environment_id: ${{ secrets.CHECKMARX_ENVIRONMENT_ID }}  # Your DAST Environment ID from GitHub secrets
        environment_name: ${{ secrets.CHECKMARX_ENVIRONMENT_NAME }}  # Your DAST Environment Name from GitHub secrets
        output: ./checkmarx_output  # Path to save output, can be customized
        verbose: true  # Optional: Enable detailed logs
        fail_on: Critical  # Fail the workflow if Critical vulnerabilities are found
        url: http://testfire.net  # The URL to scan (provided in the question)
